# Generated by Django 5.0.1 on 2024-01-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tc',
        ),
    ]
