# Generated by Django 5.0.1 on 2024-01-27 17:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_name_yourmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourmodel',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
