# Generated by Django 5.0.1 on 2024-01-27 20:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_yourmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourmodel',
            name='itemname',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
